### ISSUE TITLE
Share the source code of the executable file

### ISSUE THREAD

**Issue by smushy129** [syto203/uebersicht-FanBar-widget#2]
Please share the source code of the executable file. Source cannot be inspected if the source is just the exectable.

**Comment by syto203** [comment]
I understand you trying to take security seriously, but did you actually try reading the README of the widget?

> uses [osx-cpu-temp](https://github.com/syto203/osx-cpu-temp/tree/special) for Fan and Temperature readings since Apple stopped providing builtin access to fan metrics.

follow the hyperlink to the tool’s source. The binary is available for convenience but you can always build it yourself.

I don’t know the compatibility with current macOS (Monterey). I suggest building the one from my fork and testing it. 

If it didn’t work please let’s me know and I’ll look at it as soon as I can.
